import { i18nSubPath } from 'src/utils/common';

interface Navigation {
  label: string;
  icon: string;
  available: boolean;
  route: string;
}

const i18n = i18nSubPath('components.navigations');

export const MAIN_NAVIGATIONS: Navigation[] = [
  {
    label: i18n('main.devices'),
    icon: 'mdi-cellphone',
    available: true,
    route: 'home',
  },
  {
    label: i18n('main.growth'),
    icon: 'mdi-sprout',
    available: false,
    route: 'growth',
  },
  {
    label: i18n('main.mall'),
    icon: 'mdi-shopping',
    available: false,
    route: 'mall',
  },
  {
    label: i18n('main.me'),
    icon: 'person',
    available: true,
    route: 'me',
  },
];

export const STACK_NAVIGATIONS: Navigation[] = [
  {
    label: i18n('stack.about'),
    icon: 'information',
    available: true,
    route: 'about',
  },
  {
    label: i18n('stack.auth'),
    icon: 'lock',
    available: true,
    route: 'auth',
  },
  {
    label: i18n('stack.chat'),
    icon: 'chat',
    available: true,
    route: 'chat',
  },
  {
    label: i18n('stack.chatVoiceCall'),
    icon: 'mdi-phone',
    available: true,
    route: 'chat-voice-call',
  },
  {
    label: i18n('stack.chatMuteSettings'),
    icon: 'mdi-volume-off',
    available: true,
    route: 'chat-mute-settings',
  },
  {
    label: i18n('stack.profile'),
    icon: 'account-circle',
    available: true,
    route: 'profile',
  },
  {
    label: i18n('stack.profileEdit'),
    icon: 'mdi-account-edit',
    available: true,
    route: 'profile-edit',
  },
  {
    label: i18n('stack.profileChangePassword'),
    icon: 'lock',
    available: true,
    route: 'profile-change-password',
  },
  {
    label: i18n('stack.profileChangePhone'),
    icon: 'mdi-phone',
    available: true,
    route: 'profile-change-phone',
  },
  {
    label: i18n('stack.deviceConfig'),
    icon: 'cog',
    available: true,
    route: 'device-config',
  },
  {
    label: i18n('stack.devices'),
    icon: 'mdi-cellphone',
    available: true,
    route: 'devices',
  },
  {
    label: i18n('stack.deviceConfigVoice'),
    icon: 'mdi-account-voice',
    available: true,
    route: 'device-config-voice',
  },
  {
    label: i18n('stack.deviceConfigLanguage'),
    icon: 'mdi-translate',
    available: true,
    route: 'device-config-language',
  },
  {
    label: i18n('stack.deviceConfigPersonality'),
    icon: 'mdi-tune-variant',
    available: true,
    route: 'device-config-personality',
  },
  {
    label: i18n('stack.deviceConfigPersonalityDetail'),
    icon: 'mdi-tune-variant',
    available: true,
    route: 'device-config-personality-detail',
  },
  {
    label: i18n('stack.settings'),
    icon: 'cog',
    available: true,
    route: 'settings',
  },
  {
    label: i18n('stack.messages'),
    icon: 'email',
    available: false,
    route: 'messages',
  },
  {
    label: i18n('stack.orders'),
    icon: 'receipt',
    available: false,
    route: 'orders',
  },
  {
    label: i18n('stack.help'),
    icon: 'help',
    available: false,
    route: 'help',
  },
  {
    label: i18n('stack.settingsVoiceprint'),
    icon: 'mdi-account-voice',
    available: true,
    route: 'settings-voiceprint',
  },
  {
    label: i18n('stack.settingsVoiceprintDetail'),
    icon: 'mdi-account-voice',
    available: true,
    route: 'settings-voiceprint-detail',
  },
  {
    label: i18n('stack.settingsVoiceprintNew'),
    icon: 'mdi-microphone-plus',
    available: true,
    route: 'settings-voiceprint-new',
  },
  {
    label: i18n('stack.settingsVoiceprintTest'),
    icon: 'mdi-microphone',
    available: true,
    route: 'settings-voiceprint-test',
  },
  {
    label: i18n('stack.familyGroups'),
    icon: 'mdi-account-group',
    available: true,
    route: 'family-groups',
  },
  {
    label: i18n('stack.familyGroupDetail'),
    icon: 'mdi-account-group',
    available: true,
    route: 'family-group-detail',
  },
  {
    label: i18n('stack.familyGroupMember'),
    icon: 'mdi-account',
    available: true,
    route: 'family-group-member',
  },
  {
    label: i18n('stack.familyGroupInvite'),
    icon: 'mdi-qrcode',
    available: true,
    route: 'family-group-invite',
  },
  {
    label: i18n('stack.familyGroupChildEdit'),
    icon: 'mdi-account-edit',
    available: true,
    route: 'family-group-child-edit',
  },
  {
    label: i18n('stack.familyGroupCreate'),
    icon: 'mdi-account-plus',
    available: true,
    route: 'family-group-create',
  },
  {
    label: i18n('stack.familyGroupJoin'),
    icon: 'mdi-account-plus',
    available: true,
    route: 'family-group-join',
  },
  {
    label: i18n('stack.addVirtualDevice'),
    icon: 'mdi-plus-circle',
    available: true,
    route: 'add-virtual-device',
  },
  {
    label: i18n('stack.messageDetail'),
    icon: 'email',
    available: false,
    route: 'message-detail',
  },
  {
    label: i18n('stack.chatHistory'),
    icon: 'history',
    available: true,
    route: 'chat-history',
  },
  {
    label: i18n('stack.growthData'),
    icon: 'mdi-sprout',
    available: true,
    route: 'growth-data',
  },
  {
    label: i18n('stack.helpFaq'),
    icon: 'mdi-frequently-asked-questions',
    available: true,
    route: 'help-faq',
  },
  {
    label: i18n('stack.helpFeedback'),
    icon: 'mdi-message-alert',
    available: true,
    route: 'help-feedback',
  },
  {
    label: i18n('stack.deviceConfigWifi'),
    icon: 'mdi-wifi',
    available: true,
    route: 'device-config-wifi',
  },
  {
    label: i18n('stack.deviceConfigUpdate'),
    icon: 'mdi-update',
    available: true,
    route: 'device-config-firmware',
  },
  {
    label: i18n('stack.deviceConfigAbout'),
    icon: 'mdi-information-outline',
    available: true,
    route: 'device-config-about',
  },
  {
    label: i18n('stack.settingsAddresses'),
    icon: 'mdi-map-marker',
    available: true,
    route: 'settings-addresses',
  },
  {
    label: i18n('stack.settingsAppLanguage'),
    icon: 'mdi-translate',
    available: true,
    route: 'settings-app-language',
  },
  {
    label: i18n('stack.settingsNotifications'),
    icon: 'mdi-bell',
    available: true,
    route: 'settings-notifications',
  },
  {
    label: i18n('stack.settingsGeneral'),
    icon: 'mdi-tune',
    available: true,
    route: 'settings-general',
  },
  {
    label: i18n('stack.settingsPrivacy'),
    icon: 'mdi-shield-lock',
    available: true,
    route: 'settings-privacy',
  },
  {
    label: i18n('stack.settingsPermissions'),
    icon: 'mdi-key',
    available: true,
    route: 'settings-permissions',
  },
  {
    label: i18n('stack.settingsWordFilter'),
    icon: 'mdi-filter',
    available: true,
    route: 'settings-word-filter',
  },
  {
    label: i18n('stack.settingsClearCache'),
    icon: 'mdi-broom',
    available: true,
    route: 'settings-clear-cache',
  },
  {
    label: i18n('stack.settingsNetwork'),
    icon: 'mdi-web',
    available: true,
    route: 'settings-network',
  },
  {
    label: i18n('stack.settingsStorage'),
    icon: 'mdi-harddisk',
    available: true,
    route: 'settings-storage',
  },
  {
    label: i18n('stack.settingsPrivacyPolicy'),
    icon: 'mdi-file-document',
    available: true,
    route: 'settings-privacy-policy',
  },
  {
    label: i18n('stack.settingsTermsOfService'),
    icon: 'mdi-file-document',
    available: true,
    route: 'settings-terms-of-service',
  },
  {
    label: i18n('stack.settingsUserAgreement'),
    icon: 'mdi-file-document',
    available: true,
    route: 'settings-user-agreement',
  },
  {
    label: i18n('stack.settingsInfoList'),
    icon: 'mdi-format-list-bulleted',
    available: true,
    route: 'settings-info-list',
  },
  {
    label: i18n('stack.onboarding'),
    icon: 'mdi-rocket-launch',
    available: true,
    route: 'onboarding-complete',
  },
  {
    label: i18n('stack.messages'),
    icon: 'mdi-message-text',
    available: true,
    route: 'messages',
  },
  {
    label: i18n('stack.messageDetail'),
    icon: 'mdi-message-text',
    available: true,
    route: 'message-detail',
  },
  {
    label: i18n('stack.messagesActivity'),
    icon: 'mdi-message-text',
    available: true,
    route: 'messages-activity',
  },
  {
    label: i18n('stack.orders'),
    icon: 'mdi-shopping',
    available: true,
    route: 'orders',
  },
  {
    label: i18n('stack.help'),
    icon: 'mdi-help-circle',
    available: true,
    route: 'help',
  },
  {
    label: i18n('stack.helpFaq'),
    icon: 'mdi-frequently-asked-questions',
    available: true,
    route: 'help-faq',
  },
  {
    label: i18n('stack.helpFeedback'),
    icon: 'mdi-message-alert',
    available: true,
    route: 'help-feedback',
  },
  {
    label: i18n('stack.settingsAddresses'),
    icon: 'mdi-map-marker',
    available: true,
    route: 'settings-addresses',
  },
  {
    label: i18n('stack.settingsAppLanguage'),
    icon: 'mdi-web',
    available: true,
    route: 'settings-language',
  },
  {
    label: i18n('stack.settingsNotifications'),
    icon: 'mdi-bell',
    available: true,
    route: 'settings-notifications',
  },
  {
    label: i18n('stack.settingsGeneral'),
    icon: 'mdi-cog',
    available: true,
    route: 'settings-general',
  },
  {
    label: i18n('stack.settingsPrivacy'),
    icon: 'mdi-shield',
    available: true,
    route: 'settings-privacy',
  },
  {
    label: i18n('stack.settingsPermissions'),
    icon: 'mdi-lock',
    available: true,
    route: 'settings-permissions',
  },
  {
    label: i18n('stack.settingsWordFilter'),
    icon: 'mdi-filter',
    available: true,
    route: 'settings-word-filter',
  },
  {
    label: i18n('stack.settingsClearCache'),
    icon: 'mdi-broom',
    available: true,
    route: 'settings-clear-cache',
  },
  {
    label: i18n('stack.settingsNetwork'),
    icon: 'mdi-wifi',
    available: true,
    route: 'settings-network',
  },
  {
    label: i18n('stack.settingsStorage'),
    icon: 'mdi-database',
    available: true,
    route: 'settings-storage',
  },
  {
    label: i18n('stack.settingsInfoList'),
    icon: 'mdi-information',
    available: true,
    route: 'settings-info-list',
  },
  {
    label: i18n('stack.settingsPrivacyPolicy'),
    icon: 'mdi-file-document',
    available: true,
    route: 'settings-privacy-policy',
  },
  {
    label: i18n('stack.settingsTermsOfService'),
    icon: 'mdi-file-document',
    available: true,
    route: 'settings-terms-of-service',
  },
  {
    label: i18n('stack.settingsUserAgreement'),
    icon: 'mdi-file-document',
    available: true,
    route: 'settings-user-agreement',
  },
];
